#!/system/bin/sh

# change Governor
 echo "hybrid" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;

# change IO Scheduler
for i in `ls /sys/block/mmcblk*`
do
  echo "deadline" > $i/queue/scheduler
done
